### ISSUE TITLE
[FEAT] 게시물 수정, 삭제 view

### ISSUE THREAD

**Issue by InseonYoon** [DevLife-F1I4/DevLife#43]
## 📖 Describe
기존에 구현한 수정, 삭제 기능이 화면단에서 제대로 동작하는지 확인합니다.

## ✅ TODO

- [x] 게시글 상세조회 aside 로그인 정보 적용 안되는 문제 해결
- [x] 수정, 삭제 버튼 생성
- [x] 수정, 삭제 기능 연결
- [ ] 좋아요 기능 구현
----------------------------------
- [ ] TODO

**Comment by InseonYoon** [comment]
- 수정시 카테고리 변경해도 적용되지 않음
- 삭제시 계정 정보에 관계없이 401에러가 발생하지만 글 삭제 자체는 정상적으로 이루어짐
위 2개의 오류 해결 필요
